int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int tired(int s, int d);
int is_prime_number(int n);
int loop(int s, int d);
int is_palindrome(char *s);
int lenght(char *s);
int haha(char *s, int e, int i, int q);
int wildcmp(char *s1, char *s2);
